
services:
  web:
    container_name: allicode-node
    build: .
    env_file: .env
    ports:
      - "3003:3003" 
    depends_on:
      db:
        condition: service_healthy 
      adminer:
        condition: service_started
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: allicode-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ieee_ies_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    container_name: allicode-adminer
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db